export
    const
        IS_LOADING = "IS_LOADING",
        FETCHED_BREWERIES = "FETCHED_BREWERIES",
        IS_MONITORING = "IS_MONITORING",
        ERROR_OCCURRED = "ERROR_OCCURRED",
        CLEAR_ERROR = "CLEAR_ERROR";